(function () {
  var html = [
    '<footer class="site-footer" id="siteFooter">',
    '  <div class="footer-inner">',
    '    <div class="footer-top">',
    '      <div class="footer-brand">',
    '        <a href="./" class="footer-wordmark">',
    '          <span class="footer-wordmark-base">Nuanced Design</span>',
    '          <span class="footer-wordmark-fill" aria-hidden="true">Nuanced Design</span>',
    '        </a>',
    '        <p class="footer-tag">Human-centered design work<br>Adding the human touch in the AI era.</p>',
    '      </div>',
    '      <nav class="footer-nav" aria-label="Footer navigation">',
    '        <p class="footer-col-title">Explore</p>',
    '        <a href="./#featuredWork">Featured Work</a>',
    '        <a href="./#process">Process</a>',
    '        <a href="./#about">About</a>',
    '        <a href="./versions.html">The Story</a>',
    '        <a href="./#archive">Archive</a>',
    '        <a href="./#pricing">Pricing</a>',
    '      </nav>',
    '      <nav class="footer-nav footer-studios" aria-label="Nuanced Studios">',
    '        <p class="footer-col-title">Nuanced Studios</p>',
    '        <p class="footer-studios-desc">Homegrown apps built by Nuanced Design &mdash; designed, built, and shipped in-house.</p>',
    '        <a class="footer-studios-link" href="./nuanced-studios.html">Explore the studio <span aria-hidden="true">&rarr;</span></a>',
    '      </nav>',
    '      <div class="footer-contact">',
    '        <p class="footer-col-title">Contact</p>',
    '        <a href="mailto:hello@nuanceddesign.com">hello@nuanceddesign.com</a>',
    '        <a href="tel:6074445455">(607) 444-5455</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-bottom">',
    '      <p class="footer-copyright">&copy; 2011&ndash;2026 Nuanced Design<br>Binghamton, NY<br>Proudly made with love in the USA 🇺🇸</p>',
    '      <a class="footer-version" href="./versions.html" title="View site version history">v3.0</a>',
    '    </div>',
    '    <div class="footer-legal">',
    '      <a href="./privacy-policy.html">Privacy Policy</a>',
    '      <a href="./terms.html">Terms &amp; Conditions</a>',
    '      <a href="./cookie-policy.html">Cookie Policy</a>',
    '      <a href="./legal.html">Legal</a>',
    '    </div>',
    '  </div>',
    '</footer>'
  ].join('\n');

  document.currentScript.insertAdjacentHTML('afterend', html);
})();
